-- DDL y RLS para `public.asesores`
-- Ejecuta en el SQL Editor de Supabase

create table if not exists public.asesores (
  id_asesor bigint generated by default as identity primary key,
  nombre_asesor text not null,
  correo_asesor text not null,
  telefono_asesor text not null,
  direccion_asesor text,
  municipio_asesor text,
  rfc_asesor text,
  nacionalidad_asesor text,
  genero_asesor text,
  created_at timestamptz not null default now()
);

-- Índice único por correo (case-insensitive)
create unique index if not exists asesores_correo_unique_idx
  on public.asesores (lower(correo_asesor));

-- RLS: permitir a cualquier usuario autenticado insertar y leer
alter table public.asesores enable row level security;

do $$ begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'asesores' and policyname = 'asesores_select_all_authenticated') then
    create policy "asesores_select_all_authenticated" on public.asesores
      for select to authenticated using (true);
  end if;
end $$;

do $$ begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'asesores' and policyname = 'asesores_insert_authenticated') then
    create policy "asesores_insert_authenticated" on public.asesores
      for insert to authenticated with check (true);
  end if;
end $$;

-- (Opcional) permitir update/delete solo a roles con permisos elevados
-- create policy "asesores_update_admin" on public.asesores for update to service_role using (true);
-- create policy "asesores_delete_admin" on public.asesores for delete to service_role using (true);
